name: Build and deploy
on:
  push:
    branches:
      - master

jobs:
  Build-And-Deploy:
    runs-on: ubuntu-20.04
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Fetch tags
        shell: bash
        run: git fetch --tags -f
      - name: Download Hugo
        run: wget --retry-connrefused --waitretry=1 --read-timeout=20 https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb --output-document=hugo.deb
        env:
          HUGO_VERSION: "0.73.0"
      - name: List files
        run: ls -ahl
      - name: Install Hugo
        run: sudo dpkg -i hugo.deb
      - name: Print Hugo version
        run: hugo version
      - name: Remove Hugo Installer
        run: rm hugo.deb
      - name: Build slides with hugo
        run: hugo
      - name: Deploy website
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          git-config-name: Danilo Pianini
          git-config-email: danilo.pianini@unibo.it
          repository-name: pslab-unibo/pslab-unibo.github.io
          branch: master
          folder: public
